return {}
-- return {
--   {
--     "m4xshen/hardtime.nvim",
--     event = "VeryLazy",
--     dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
--     opts = {},
--   },
--   {
--     "tris203/precognition.nvim",
--     event = "VeryLazy",
--     opts = {},
--   },
-- }
